### Copies and views

In [2]:
import numpy as np

In [3]:
students_ids_number=np.array([1111,1212,1313,1414,1515,1616,1717,1818])
print(students_ids_number)

[1111 1212 1313 1414 1515 1616 1717 1818]


In [7]:
students_ids_number_reg=students_ids_number
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_reg",id(students_ids_number_reg))
print("same id: ",id(students_ids_number)==id(students_ids_number_reg))

id of students_ids_number 123468640699952
id of students_ids_number_reg 123468640699952
same id:  True


In [9]:
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_reg",id(students_ids_number_reg))
print("same id: ",id(students_ids_number)==id(students_ids_number_reg))

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]
id of students_ids_number 123468640699952
id of students_ids_number_reg 123468640699952
same id:  True


Como vemos, se modifica en los dos. "=" NO CREA UNA COPIA

In [11]:
students_ids_number_cp=students_ids_number.copy()
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_cp",id(students_ids_number_cp))
print("same id: ",id(students_ids_number)==id(students_ids_number_cp))

id of students_ids_number 123468640699952
id of students_ids_number_cp 123468633586640
same id:  False
