### Indexing and slicing

In [2]:
import numpy as np

In [4]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr=arr.reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(arr[1,1])

5


In [10]:
print(arr[0])

[0 1 2 3]


In [11]:
arr3d=np.reshape(np.arange(3*4*5),(3,4,5))
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [12]:
print(arr3d[0,2,3])

13


In [15]:
print(arr3d[-1,-1,-1])

59


In [17]:
print(arr3d[:2,:2,:2])

[[[ 0  1]
  [ 5  6]]

 [[20 21]
  [25 26]]]


In [22]:
print(arr3d[::,::-1,::-1])

[[[19 18 17 16 15]
  [14 13 12 11 10]
  [ 9  8  7  6  5]
  [ 4  3  2  1  0]]

 [[39 38 37 36 35]
  [34 33 32 31 30]
  [29 28 27 26 25]
  [24 23 22 21 20]]

 [[59 58 57 56 55]
  [54 53 52 51 50]
  [49 48 47 46 45]
  [44 43 42 41 40]]]
