### Reshaping arrays

In [1]:
import numpy as np

In [3]:
first_arr=np.arange(1,13)
print(first_arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
reshape_arr=first_arr.reshape(3,4)
print(reshape_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
reshape_arr2=first_arr.reshape(3,2,2 )
print(reshape_arr2)
print("\nDimensions of reshape_arr2 is",reshape_arr2.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

Dimensions of reshape_arr2 is 3


In [10]:
second_arr=np.array([[1,2],[3,4],[5,6]])
second_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
reshape_arr3=second_arr.reshape(-1)
reshape_arr3

array([1, 2, 3, 4, 5, 6])

Hay otras maneras de aplanar un array. Se puede usar reval o flatten. Reval es view con lo cual cambia el original y es mas eficiente. Sin embargo, flatten crea una copia aplanada.

In [17]:
arr=np.arange(1,13).reshape(3,4)
print(arr)
arr_ravel=np.ravel(arr)
print("arr_ravel",arr_ravel, arr_ravel.shape)
print("arr",arr, arr.shape)
arr_flattem = arr.flatten()
print("arr_flattem",arr_flattem, arr_flattem.shape)
print("arr",arr, arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
arr_ravel [ 1  2  3  4  5  6  7  8  9 10 11 12] (12,)
arr [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
arr_flattem [ 1  2  3  4  5  6  7  8  9 10 11 12] (12,)
arr [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
