### Joining and splitting ararys

In [1]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1)
print(arr2)
arr= np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)
arr4=np.array([[7,8,9],[10,11,12]])
print(arr4)
arr5=np.concatenate((arr3,arr4),axis=0)
print(arr5)
arr6=np.concatenate((arr3,arr4),axis=1)
print(arr6)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [5]:
st_arr=np.stack((arr1,arr2))
print(st_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
st_arr2=np.stack((arr1,arr2),axis=1)
print(st_arr2)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [7]:
vst_arr=np.vstack((arr1,arr2))
print(vst_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
hst_arr=np.hstack((arr1,arr2))
print(hst_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
fifth_arr = np.arange(1,13)
print(fifth_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
sp_arr=np.split(fifth_arr,2)
print(sp_arr)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]


In [10]:
print(sp_arr[1])

[4 5 6]


In [ ]:
sp_arr2=np.array_split(fifth_arr,5)
sp_arr2

#ARRAY_SPLIT() TE SPLITEA LA MATRIZ EN 5 AUNQUE NO DE EXACTO

[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

In [21]:
hs_arr=np.hsplit(fifth_arr,2)
print(hs_arr)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]


In [35]:
vst_arr=np.vsplit(fifth_arr.reshape(3,4),3) 
print(vst_arr)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
