### Adding, removing and sorting elements

In [3]:
import numpy as np

In [2]:
first_arr=np.arange(1,11)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
new_first_arr=np.append(first_arr,11)
new_first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
second_arr=np.arange(12,22)
second_arr


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [9]:
new_second_arr=np.insert(second_arr,(0,10),[-100,-100])
new_second_arr

array([-100,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       -100])

In [12]:
third_arr=np.arange(1,6)
third_arr

array([1, 2, 3, 4, 5])

In [13]:
del_arr=np.delete(third_arr,2)
del_arr

array([1, 2, 4, 5])

In [16]:
fourth_arr=np.random.randint(1,100,100)
fourth_arr

array([ 1, 91, 10, 78, 93, 40, 42,  1, 15, 45, 81, 56, 39, 54, 69,  7, 44,
       15,  2, 92, 19, 72, 45, 84, 48, 64, 27, 13, 88, 16, 61, 86, 46, 19,
       60, 91, 42, 96, 71, 83,  2, 92, 12, 92, 52, 37,  9, 59, 73, 59, 92,
        7, 54, 83,  3, 73, 37, 45, 64, 13, 99, 76, 49,  6, 40, 58, 32, 87,
        4, 89, 15, 36, 40, 61, 45, 62, 83, 64, 26, 39, 24, 25, 98, 44, 19,
       55, 98, 65, 39, 55, 70, 45, 76, 15, 60, 51, 70, 60, 76, 45])

In [24]:
sort_arr=np.sort(fourth_arr)
sort_arr

#Ordenar de mayor a menor se hace asi: 
sort_arr_2=np.sort(fourth_arr)[::-1]
sort_arr_2

array([99, 98, 98, 96, 93, 92, 92, 92, 92, 91, 91, 89, 88, 87, 86, 84, 83,
       83, 83, 81, 78, 76, 76, 76, 73, 73, 72, 71, 70, 70, 69, 65, 64, 64,
       64, 62, 61, 61, 60, 60, 60, 59, 59, 58, 56, 55, 55, 54, 54, 52, 51,
       49, 48, 46, 45, 45, 45, 45, 45, 45, 44, 44, 42, 42, 40, 40, 40, 39,
       39, 39, 37, 37, 36, 32, 27, 26, 25, 24, 19, 19, 19, 16, 15, 15, 15,
       15, 13, 13, 12, 10,  9,  7,  7,  6,  4,  3,  2,  2,  1,  1])

In [68]:
fiveth_arr=np.random.randint(1,50,(100,100))
fiveth_arr #Te pone el shape porque no muestra toda la matriz, entonces te indica el tamaño que tiene

array([[32, 16, 31, ..., 10,  3, 21],
       [22, 44,  5, ..., 11,  6, 42],
       [ 7,  2, 13, ..., 35, 15, 31],
       ...,
       [24, 34, 28, ..., 27, 36,  4],
       [39, 25, 25, ..., 20, 23,  3],
       [40, 10, 12, ..., 26, 39,  2]], shape=(100, 100))

In [70]:
sort_arr3=np.sort(fiveth_arr)
sort_arr3

array([[ 1,  1,  2, ..., 48, 48, 49],
       [ 1,  2,  2, ..., 46, 47, 48],
       [ 1,  2,  2, ..., 48, 48, 49],
       ...,
       [ 1,  1,  2, ..., 49, 49, 49],
       [ 1,  1,  1, ..., 48, 49, 49],
       [ 1,  2,  2, ..., 48, 48, 49]], shape=(100, 100))

In [75]:
sort_arr4=np.sort(fiveth_arr,0)
sort_arr4

array([[ 1,  1,  1, ...,  1,  1,  2],
       [ 1,  2,  2, ...,  1,  2,  2],
       [ 1,  2,  2, ...,  2,  2,  3],
       ...,
       [46, 48, 48, ..., 48, 49, 48],
       [47, 49, 49, ..., 48, 49, 48],
       [49, 49, 49, ..., 49, 49, 49]], shape=(100, 100))

In [76]:
colors=np.array(['orange','green','yellow','white','black','pink','blue'])
colors


array(['orange', 'green', 'yellow', 'white', 'black', 'pink', 'blue'],
      dtype='<U6')

In [80]:
sort_colors=np.sort(colors)
print(sort_colors)

['black' 'blue' 'green' 'orange' 'pink' 'white' 'yellow']
