### Creating arrays from Lists and other Python structures

In [1]:
import numpy as np

In [2]:
first_list=[1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
first_array=np.array(first_list)
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
second_list=[1,2,3,-1.23,50,128000.56,4.56]
second_array=np.array(second_list)
second_array
#La funcion np.array automaticamente hace el array del tipo correcto

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [9]:
third_list=[1,2,3,-1.23,50,128000.56,"Ann","111111","Peter","111112","Susan","111113","John","111114"]
third_array=np.array(third_list)
third_array
#Convierte todoe en strings

array(['1', '2', '3', '-1.23', '50', '128000.56', 'Ann', '111111',
       'Peter', '111112', 'Susan', '111113', 'John', '111114'],
      dtype='<U32')

In [10]:
first_tuple=(1,2,3,4,5,6,7,8,9,10)
array_from_tuple=np.array(first_tuple)
array_from_tuple

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
array_from_tuple.dtype

dtype('int64')