### Intrisic NumPy array creation

In [1]:
import numpy as np


In [4]:
integers = np.arange(10)
integers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
integers_2= np.arange(0,10)
integers_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
integers_3= np.arange(0,10,2)
integers_3


array([0, 2, 4, 6, 8])

In [ ]:
integers_4= np.linspace(0,5)
integers_4 #Hace una secuencia de 50 elementos

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [ ]:
integers_5= np.linspace(0,100,5)
integers_5

In [21]:
integers_6= np.linspace(0,100,5,endpoint=False)
integers_7= np.linspace(0,100,5,endpoint=True)
print(integers_6,integers_7)

[ 0. 20. 40. 60. 80.] [  0.  25.  50.  75. 100.]


In [ ]:
random_nums = np.random.rand(10,4)
random_nums

array([[0.77248538, 0.50062889, 0.16926299, 0.27998764],
       [0.81161654, 0.11723265, 0.54824177, 0.75227979],
       [0.34637547, 0.58089725, 0.31970169, 0.32880303],
       [0.1203343 , 0.19390062, 0.30946042, 0.64900919],
       [0.85708423, 0.30324762, 0.96261942, 0.15854984],
       [0.47214771, 0.85532432, 0.78781864, 0.65944412],
       [0.09794274, 0.81704261, 0.47315128, 0.73265854],
       [0.85924996, 0.97048923, 0.98028136, 0.41043201],
       [0.66523912, 0.46073062, 0.20595631, 0.61809587],
       [0.75100093, 0.85911179, 0.93933353, 0.7292923 ]])

In [23]:
random_ints = np.random.randint(0,100,10)
random_ints

array([98, 89, 94, 39, 17, 82, 31,  7, 14, 48])