### Array types and conversions between types

In [1]:
import numpy as np

In [ ]:
integers = np.array([10,20,30,40,50])
print(integers)

[10 20 30 40 50]


In [5]:
integers[0]

np.int64(10)

In [6]:
integers[0] = 100
integers

array([100,  20,  30,  40,  50])

In [ ]:
integers[0]=21.8
integers
#Trunca a int porque la tupla es de enteros

array([21, 20, 30, 40, 50])

In [9]:
integers.dtype

dtype('int64')

In [23]:
integers = integers.astype(np.float128)
print(f"Aunque ya se le indicara que era 21.8 al ser int, no se comvierte cuando la ponemos como float{integers}")

integers[0] = 21.8
print(integers)

Aunque ya se le indicara que era 21.8 al ser int, no se comvierte cuando la ponemos como float[21.8 20.  30.  40.  50. ]
[21.8 20.  30.  40.  50. ]


In [27]:
smaller_integers = np.array(integers, dtype=np.int8)
print(integers.nbytes,smaller_integers.nbytes)

80 5


In [ ]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])
print(floats)
print(floats.dtype)
#Numpy automaticamente lo convierte a float64

[1.2 2.3 3.4 5.1 8.3]
float64
