### Transpose like operations

In [1]:
import numpy as np

In [2]:
arr1_2d=np.arange(12).reshape(3,4)
arr1_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(arr1_2d)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [18]:
arr2_3d=np.arange(8).reshape(2,2,2)
arr2_3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
print(np.transpose(arr2_3d))
print("\n")
print(np.transpose(arr2_3d,(0,1,2)))
print("\n")
print(np.transpose(arr2_3d,(0,2,1)))
print("\n")
print(np.transpose(arr2_3d,(1,0,2)))
print("\n")
print(np.transpose(arr2_3d,(1,2,0)))

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]


In [20]:
np.moveaxis(arr2_3d,0,-1)

array([[[0, 4],
        [1, 5]],

       [[2, 6],
        [3, 7]]])

In [21]:
np.swapaxes(arr2_3d,0,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])