### Aggregate functions

In [1]:
import numpy as np

In [4]:
arr1=np.arange(10,110,10)
arr2=np.arange(10,100,10).reshape(3,3)
arr3=np.arange(10,110,10).reshape(2,5)
print(arr1)
print(arr2)
print(arr3)

[ 10  20  30  40  50  60  70  80  90 100]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [9]:
arr1.sum()

np.int64(550)

In [12]:
print(arr2.sum(axis=0)) #sum of each column
print(arr2.sum(axis=1)) #sum of each row

[120 150 180]
[ 60 150 240]


In [13]:
arr1.prod()

np.int64(36288000000000000)

In [15]:
print(arr3.prod(axis=0)) #product of each column
print(arr3.prod(axis=1)) #product of each row

[ 600 1400 2400 3600 5000]
[  12000000 3024000000]


In [16]:
np.average(arr1)

np.float64(55.0)

In [18]:
print(arr2.min(),arr2.max())

10 90


In [20]:
print(arr1.mean(),np.std(arr1))

55.0 28.722813232690143
