### How to get unique items and counts

In [1]:
import numpy as np

In [20]:
arr1=np.random.randint(1,10,20)
arr1

array([4, 3, 3, 6, 8, 1, 5, 2, 7, 6, 2, 1, 5, 8, 2, 4, 5, 3, 6, 6])

In [23]:
np.unique(arr1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
arr2=np.array([[1,2,1,4,5],[1,7,1,9,10],[1,2,1,4,5],[1,4,1,6,7]])
arr2

array([[ 1,  2,  1,  4,  5],
       [ 1,  7,  1,  9, 10],
       [ 1,  2,  1,  4,  5],
       [ 1,  4,  1,  6,  7]])

In [37]:
np.unique(arr2)

array([ 1,  2,  4,  5,  6,  7,  9, 10])

In [39]:
np.unique(arr2,return_counts=True)

(array([ 1,  2,  4,  5,  6,  7,  9, 10]), array([8, 2, 3, 2, 1, 2, 1, 1]))

In [ ]:
np.unique(arr2,axis=0) #Devuelve las filas únicas

array([[ 1,  2,  1,  4,  5],
       [ 1,  4,  1,  6,  7],
       [ 1,  7,  1,  9, 10]])

In [ ]:
np.unique(arr2,axis=1) #Devuelve las columnas únicas

array([[ 1,  2,  4,  5],
       [ 1,  7,  9, 10],
       [ 1,  2,  4,  5],
       [ 1,  4,  6,  7]])

In [44]:
np.unique(arr2,axis=0,return_index=True)

(array([[ 1,  2,  1,  4,  5],
        [ 1,  4,  1,  6,  7],
        [ 1,  7,  1,  9, 10]]),
 array([0, 3, 1]))